# source: https://github.com/josecelano/svelte-deploy-with-github-actions/tree/master/.github/workflows
# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          folder: public

permissions:
  contents: write
